import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { motion, AnimatePresence } from "framer-motion";
import Sidebar from "../components/Sidebar";
import FeedbackModal from "../components/FeedbackModal";
import FileUpload from "../components/FileUpload";
import ChatInterface from "../components/ChatInterface";
import SummaryPanel from "../components/SummaryPanel";
import QuizPanel from "../components/QuizPanel";
import FlashcardPanel from "../components/FlashcardPanel";
import { listDocuments, listChatSessions } from "../services/api";
import {
  FiCheckCircle, FiBookOpen,
  FiUploadCloud, FiMessageSquare, FiFileText, FiAward, FiLayers,
  FiBell, FiX, FiAlertCircle, FiMenu, FiLogOut, FiMessageCircle,
} from "react-icons/fi";

// ── Terms & Conditions Modal ──────────────────────────────────────────────────
function TermsModal({ onAccept }) {
  const [scrolled, setScrolled] = useState(false);

  const handleScroll = (e) => {
    const el = e.target;
    if (el.scrollHeight - el.scrollTop - el.clientHeight < 40) setScrolled(true);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: "rgba(3,0,20,0.85)", backdropFilter: "blur(12px)" }}>
      <motion.div
        initial={{ opacity: 0, scale: 0.94, y: 20 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
        className="w-full max-w-lg rounded-2xl flex flex-col"
        style={{
          background: "linear-gradient(145deg, #0e0b1f 0%, #080517 100%)",
          border: "1px solid rgba(124,58,237,0.25)",
          boxShadow: "0 0 80px rgba(124,58,237,0.12), 0 24px 60px rgba(0,0,0,0.7)",
          maxHeight: "90vh",
        }}
      >
        {/* Header */}
        <div className="px-7 pt-7 pb-5 flex-shrink-0" style={{ borderBottom: "1px solid rgba(124,58,237,0.12)" }}>
          <div className="flex items-center gap-3 mb-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
              style={{ background: "linear-gradient(135deg,#7c3aed,#3b82f6)", boxShadow: "0 0 20px rgba(124,58,237,0.4)" }}>
              <FiBookOpen className="text-white text-base" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Terms of Use</h2>
              <p className="text-xs text-gray-500">StudyMate AI — Please read before continuing</p>
            </div>
          </div>
        </div>

        {/* Scrollable body */}
        <div
          className="flex-1 overflow-y-auto px-7 py-5 space-y-5 text-sm text-gray-400 leading-relaxed"
          style={{ minHeight: 0 }}
          onScroll={handleScroll}
        >
          <section>
            <h3 className="text-gray-200 font-semibold mb-1.5">1. What StudyMate AI Does</h3>
            <p>StudyMate AI is a study assistant that helps you understand your uploaded notes. It can summarize content, answer questions based on your documents, generate quizzes, and create flashcards to aid your learning.</p>
          </section>

          <section>
            <h3 className="text-gray-200 font-semibold mb-1.5">2. Not a Solver or Cheating Tool</h3>
            <p>StudyMate AI is designed for <span className="text-purple-300 font-medium">learning and understanding</span> only. It is not intended to complete assignments, solve exam questions on your behalf, or be used as an academic dishonesty tool. Use it responsibly.</p>
          </section>

          <section>
            <h3 className="text-gray-200 font-semibold mb-1.5">3. Your Uploaded Documents</h3>
            <p>Documents you upload are processed to answer your questions. Do not upload confidential, sensitive, or copyrighted material you do not have rights to. You are responsible for the content you upload.</p>
          </section>

          <section>
            <h3 className="text-gray-200 font-semibold mb-1.5">4. AI Limitations</h3>
            <p>Answers are generated by AI and grounded in your uploaded notes. They may occasionally be incomplete or inaccurate. Always verify important information with your course material and instructors.</p>
          </section>

          <section>
            <h3 className="text-gray-200 font-semibold mb-1.5">5. Privacy</h3>
            <p>Your email and account information are stored securely. We do not sell or share your personal data with third parties.</p>
          </section>

          <section>
            <h3 className="text-gray-200 font-semibold mb-1.5">6. Acceptance</h3>
            <p>By clicking "I Agree", you confirm that you have read and agree to use StudyMate AI responsibly for educational purposes only.</p>
          </section>

          {/* Fade indicator */}
          {!scrolled && (
            <p className="text-center text-xs text-purple-500 animate-pulse pt-2">Scroll down to continue ↓</p>
          )}
        </div>

        {/* Footer */}
        <div className="px-7 py-5 flex-shrink-0" style={{ borderTop: "1px solid rgba(124,58,237,0.12)" }}>
          <button
            onClick={onAccept}
            disabled={!scrolled}
            className="w-full py-3 rounded-xl font-semibold text-sm text-white flex items-center justify-center gap-2 transition-all duration-200 disabled:opacity-35 disabled:cursor-not-allowed"
            style={{
              background: scrolled
                ? "linear-gradient(135deg,#7c3aed,#5b21b6 50%,#3b82f6)"
                : "rgba(124,58,237,0.2)",
              boxShadow: scrolled ? "0 0 24px rgba(124,58,237,0.35)" : "none",
            }}
          >
            <FiCheckCircle size={15} />
            {scrolled ? "I Agree — Continue to StudyMate AI" : "Read all terms to continue"}
          </button>
        </div>
      </motion.div>
    </div>
  );
}

const SECTION_META = {
  upload:     { title: "Upload Notes",   subtitle: "Add your study material to get started",      icon: FiUploadCloud,   color: "#a78bfa" },
  chat:       { title: "Ask AI",         subtitle: "Ask questions grounded in your notes",        icon: FiMessageSquare, color: "#60a5fa" },
  summary:    { title: "AI Summary",     subtitle: "Key concepts, takeaways, and definitions",    icon: FiFileText,      color: "#34d399" },
  quiz:       { title: "Quiz Generator", subtitle: "Test your knowledge with AI-generated MCQs", icon: FiAward,         color: "#f59e0b" },
  flashcards: { title: "Flashcards",     subtitle: "Study with interactive flip cards",           icon: FiLayers,        color: "#f472b6" },
};

const TYPE_LABEL = { quiz: "Quiz", flashcards: "Flashcards", summary: "Summary" };
const TYPE_SECTION = { quiz: "quiz", flashcards: "flashcards", summary: "summary" };

function timeAgo(ts) {
  const s = (Date.now() - ts) / 1000;
  if (s < 60) return "just now";
  if (s < 3600) return `${Math.floor(s / 60)}m ago`;
  return `${Math.floor(s / 3600)}h ago`;
}

function NotificationPanel({ notifications, onClose, onNavigate, onClear }) {
  return (
    <>
      {/* Full-screen backdrop — sits below the panel, closes on click */}
      <div className="fixed inset-0" style={{ zIndex: 998 }} onClick={onClose} />

      {/* Panel — solid opaque background, above backdrop */}
      <motion.div
        initial={{ opacity: 0, y: -10, scale: 0.95 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        exit={{ opacity: 0, y: -10, scale: 0.95 }}
        transition={{ duration: 0.16, ease: [0.16, 1, 0.3, 1] }}
        className="fixed top-[68px] right-3 sm:right-5 w-[calc(100vw-24px)] sm:w-[320px] rounded-2xl"
        style={{
          zIndex: 999,
          backgroundColor: "#0d0b1e",          /* solid — no transparency */
          border: "1px solid rgba(124,58,237,0.4)",
          boxShadow: "0 0 0 1px rgba(124,58,237,0.1), 0 8px 32px rgba(0,0,0,0.8), 0 0 60px rgba(124,58,237,0.15)",
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-4 py-3"
          style={{ borderBottom: "1px solid rgba(124,58,237,0.15)" }}
        >
          <p className="text-sm font-bold text-white">Notifications</p>
          <div className="flex items-center gap-2">
            {notifications.length > 0 && (
              <button
                onClick={(e) => { e.stopPropagation(); onClear(); onClose(); }}
                className="text-[11px] font-medium px-2 py-1 rounded-lg transition-all duration-150"
                style={{ color: "#6b7280", background: "rgba(239,68,68,0)", border: "1px solid transparent" }}
                onMouseOver={(e) => {
                  e.currentTarget.style.color = "#f87171";
                  e.currentTarget.style.background = "rgba(239,68,68,0.1)";
                  e.currentTarget.style.borderColor = "rgba(239,68,68,0.25)";
                }}
                onMouseOut={(e) => {
                  e.currentTarget.style.color = "#6b7280";
                  e.currentTarget.style.background = "rgba(239,68,68,0)";
                  e.currentTarget.style.borderColor = "transparent";
                }}
              >
                Clear all
              </button>
            )}
            <button
              onClick={(e) => { e.stopPropagation(); onClose(); }}
              className="w-7 h-7 rounded-lg flex items-center justify-center transition-all duration-150"
              style={{ background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", color: "#6b7280" }}
              onMouseOver={(e) => {
                e.currentTarget.style.background = "rgba(239,68,68,0.15)";
                e.currentTarget.style.borderColor = "rgba(239,68,68,0.35)";
                e.currentTarget.style.color = "#f87171";
              }}
              onMouseOut={(e) => {
                e.currentTarget.style.background = "rgba(255,255,255,0.05)";
                e.currentTarget.style.borderColor = "rgba(255,255,255,0.1)";
                e.currentTarget.style.color = "#6b7280";
              }}
            >
              <FiX size={12} />
            </button>
          </div>
        </div>

        {/* Body */}
        {notifications.length === 0 ? (
          <div className="py-10 text-center">
            <FiBell size={24} className="mx-auto mb-3" style={{ color: "#374151" }} />
            <p className="text-sm text-gray-600 font-medium">No notifications yet</p>
            <p className="text-[11px] text-gray-700 mt-1">Completed generations appear here</p>
          </div>
        ) : (
          <div className="max-h-72 overflow-y-auto">
            {notifications.map((n) => (
              <div
                key={n.id}
                onClick={(e) => { e.stopPropagation(); if (!n.error) { onNavigate(TYPE_SECTION[n.type]); } }}
                className="flex items-start gap-3 px-4 py-3.5 transition-all duration-150"
                style={{
                  borderBottom: "1px solid rgba(255,255,255,0.05)",
                  cursor: n.error ? "default" : "pointer",
                }}
                onMouseOver={(e) => { if (!n.error) e.currentTarget.style.background = "rgba(124,58,237,0.07)"; }}
                onMouseOut={(e) => { e.currentTarget.style.background = "transparent"; }}
              >
                {/* Icon */}
                <div
                  className="w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0"
                  style={{
                    background: n.error ? "rgba(239,68,68,0.15)" : "rgba(52,211,153,0.12)",
                    border: `1px solid ${n.error ? "rgba(239,68,68,0.3)" : "rgba(52,211,153,0.25)"}`,
                  }}
                >
                  {n.error
                    ? <FiAlertCircle size={13} style={{ color: "#f87171" }} />
                    : <FiCheckCircle size={13} style={{ color: "#34d399" }} />}
                </div>

                {/* Text */}
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-semibold leading-tight" style={{ color: n.error ? "#f87171" : "#34d399" }}>
                    {n.error ? `${TYPE_LABEL[n.type]} failed` : `${TYPE_LABEL[n.type]} is ready!`}
                  </p>
                  <p className="text-[11px] mt-0.5 truncate" style={{ color: "#9ca3af" }}>{n.docName}</p>
                  {!n.error && (
                    <p className="text-[11px] font-semibold mt-1" style={{ color: "#a78bfa" }}>
                      Click to view →
                    </p>
                  )}
                  {n.error && n.msg && (
                    <p className="text-[10px] mt-0.5 truncate" style={{ color: "#6b7280" }}>{n.msg}</p>
                  )}
                </div>

                {/* Time */}
                <span className="text-[10px] flex-shrink-0 mt-0.5" style={{ color: "#4b5563" }}>
                  {timeAgo(n.timestamp)}
                </span>
              </div>
            ))}
          </div>
        )}
      </motion.div>
    </>
  );
}

export default function Dashboard() {
  const router = useRouter();
  const [user,          setUser]          = useState(null);
  const [authChecked,   setAuthChecked]   = useState(false);
  const [activeSection, setActiveSection] = useState("upload");
  const [documents,          setDocuments]          = useState([]);
  const [selectedDocId,      setSelectedDocId]      = useState(null);
  const [showTerms,          setShowTerms]          = useState(false);
  const [sessions,           setSessions]           = useState([]);
  const [selectedSessionId,  setSelectedSessionId]  = useState(null);

  // ── Background generation state ──────────────────────────────────────────────
  const [genJobs,       setGenJobs]       = useState({});        // key: `${type}_${docId}`
  const [notifications, setNotifications] = useState([]);
  const [notifOpen,     setNotifOpen]     = useState(false);
  const [sidebarOpen,   setSidebarOpen]   = useState(false);
  const [feedbackOpen,  setFeedbackOpen]  = useState(false);

  const startGeneration = useCallback(async (type, docId, apiFn, docsList) => {
    const key = `${type}_${docId}`;
    const docName = (docsList || documents).find((d) => d.doc_id === docId)?.name || "Document";
    setGenJobs((prev) => ({ ...prev, [key]: { status: "loading", result: null, docName, type } }));
    try {
      const result = await apiFn();
      setGenJobs((prev) => ({ ...prev, [key]: { status: "done", result, docName, type, timestamp: Date.now() } }));
      setNotifications((prev) => [{ id: Date.now(), type, docName, timestamp: Date.now(), read: false }, ...prev]);
    } catch (err) {
      const msg = err?.response?.data?.detail || "Generation failed.";
      setGenJobs((prev) => ({ ...prev, [key]: { status: "error", error: msg, docName, type, timestamp: Date.now() } }));
      setNotifications((prev) => [{ id: Date.now(), type, docName, timestamp: Date.now(), read: false, error: true, msg }, ...prev]);
    }
  }, [documents]);

  useEffect(() => {
    try {
      const raw = localStorage.getItem("studymate_auth");
      if (!raw) { router.replace("/login"); return; }
      const parsed = JSON.parse(raw);
      setUser(parsed);
      const accepted = localStorage.getItem(`studymate_terms_${parsed.id}`);
      if (!accepted) setShowTerms(true);
    } catch {
      router.replace("/login");
    } finally {
      setAuthChecked(true);
    }
  }, [router]);

  const handleAcceptTerms = () => {
    if (user) localStorage.setItem(`studymate_terms_${user.id}`, "1");
    setShowTerms(false);
  };

  useEffect(() => {
    if (!authChecked || !user) return;
    listDocuments(user.id)
      .then((docs) => {
        if (docs?.length) {
          setDocuments(docs);
          setSelectedDocId(docs[0].doc_id);
          setActiveSection("chat");
        }
      })
      .catch(() => {});
    listChatSessions(user.id)
      .then((data) => setSessions(data || []))
      .catch(() => {});
  }, [authChecked, user]);

  const handleSessionCreated = (session) => {
    setSessions((prev) => [session, ...prev]);
    setSelectedSessionId(session.id);
  };

  const handleSelectSession = (session) => {
    setSelectedSessionId(session.id);
    // Only scope to the session's doc if it's actually available on this device
    if (session.doc_id && documents.some((d) => d.doc_id === session.doc_id)) {
      setSelectedDocId(session.doc_id);
    }
    setActiveSection("chat");
  };

  const handleNewChat = () => {
    setSelectedSessionId(null);
  };

  if (!authChecked) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: "#030014" }}>
        <div style={{ position: "relative" }}>
          <span className="w-10 h-10 border-2 border-purple-500/20 border-t-purple-500 rounded-full animate-spin block" />
          <div className="absolute inset-0 rounded-full" style={{
            boxShadow: "0 0 20px rgba(124,58,237,0.3)",
            animation: "glow-pulse 2s ease-in-out infinite",
          }} />
        </div>
      </div>
    );
  }

  const meta = SECTION_META[activeSection];

  return (
    <>
      <Head>
        <title>StudyMate AI — Dashboard</title>
      </Head>

      <AnimatePresence>
        {showTerms && <TermsModal onAccept={handleAcceptTerms} />}
      </AnimatePresence>

      <AnimatePresence>
        {feedbackOpen && (
          <FeedbackModal user={user} onClose={() => setFeedbackOpen(false)} />
        )}
      </AnimatePresence>

      {/* Notification panel — rendered at root so no parent can clip or block it */}
      <AnimatePresence>
        {notifOpen && (
          <NotificationPanel
            notifications={notifications}
            onClose={() => setNotifOpen(false)}
            onNavigate={(section) => { setActiveSection(section); setNotifOpen(false); }}
            onClear={() => setNotifications([])}
          />
        )}
      </AnimatePresence>

      {/* Mobile sidebar overlay */}
      <AnimatePresence>
        {sidebarOpen && (
          <>
            <motion.div
              className="fixed inset-0 md:hidden"
              style={{ zIndex: 30, background: "rgba(0,0,0,0.65)", backdropFilter: "blur(4px)" }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              onClick={() => setSidebarOpen(false)}
            />
            <motion.div
              className="fixed inset-y-0 left-0 md:hidden"
              style={{ zIndex: 40 }}
              initial={{ x: -260 }}
              animate={{ x: 0 }}
              exit={{ x: -260 }}
              transition={{ type: "spring", damping: 28, stiffness: 260 }}
            >
              <Sidebar
                activeSection={activeSection}
                setActiveSection={setActiveSection}
                documents={documents}
                setDocuments={setDocuments}
                selectedDocId={selectedDocId}
                setSelectedDocId={setSelectedDocId}
                user={user}
                sessions={sessions}
                setSessions={setSessions}
                selectedSessionId={selectedSessionId}
                onSelectSession={handleSelectSession}
                onNewChat={handleNewChat}
                onClose={() => setSidebarOpen(false)}
                onFeedback={() => setFeedbackOpen(true)}
              />
            </motion.div>
          </>
        )}
      </AnimatePresence>

      <div className="flex h-screen overflow-hidden" style={{ background: "#030014" }}>

        {/* Ambient background glows */}
        <div className="fixed inset-0 pointer-events-none" style={{ zIndex: 0 }}>
          <div className="absolute top-0 right-0 w-[600px] h-[600px] rounded-full opacity-[0.04]"
            style={{ background: "radial-gradient(circle, #7c3aed, transparent)", filter: "blur(60px)" }} />
          <div className="absolute bottom-0 left-60 w-[500px] h-[500px] rounded-full opacity-[0.03]"
            style={{ background: "radial-gradient(circle, #3b82f6, transparent)", filter: "blur(60px)" }} />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[400px] rounded-full opacity-[0.02]"
            style={{ background: "radial-gradient(ellipse, #7c3aed, transparent)", filter: "blur(80px)" }} />
        </div>

        {/* Sidebar — desktop always visible, hidden on mobile (shown as overlay above) */}
        <div className="hidden md:block flex-shrink-0" style={{ position: "relative", zIndex: 10 }}>
          <Sidebar
            activeSection={activeSection}
            setActiveSection={setActiveSection}
            documents={documents}
            setDocuments={setDocuments}
            selectedDocId={selectedDocId}
            setSelectedDocId={setSelectedDocId}
            user={user}
            sessions={sessions}
            setSessions={setSessions}
            selectedSessionId={selectedSessionId}
            onSelectSession={handleSelectSession}
            onNewChat={handleNewChat}
            onFeedback={() => setFeedbackOpen(true)}
          />
        </div>

        {/* Main */}
        <div className="flex-1 flex flex-col min-w-0 overflow-hidden" style={{ position: "relative", zIndex: 1 }}>

          {/* Header */}
          <header className="header-glass flex items-center justify-between px-3 md:px-7 py-4 flex-shrink-0">
            <div className="flex items-center gap-2 md:gap-4">
              {/* Hamburger — mobile only */}
              <button
                className="md:hidden w-8 h-8 rounded-xl flex items-center justify-center flex-shrink-0 transition-all duration-150"
                style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}
                onClick={() => setSidebarOpen(true)}
              >
                <FiMenu size={15} className="text-gray-400" />
              </button>

              {/* Section info */}
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeSection}
                  initial={{ opacity: 0, y: -6 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: 6 }}
                  transition={{ duration: 0.2 }}
                >
                  <div className="flex items-center gap-2 md:gap-3">
                    <div className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
                      style={{
                        background: `${meta.color}18`,
                        border: `1px solid ${meta.color}33`,
                        boxShadow: `0 0 12px ${meta.color}18`,
                      }}>
                      <meta.icon style={{ fontSize: 14, color: meta.color }} />
                    </div>
                    <div>
                      <h1 className="text-sm md:text-base font-bold text-white leading-none">{meta.title}</h1>
                      <p className="hidden sm:block text-[11px] text-gray-600 mt-0.5">{meta.subtitle}</p>
                    </div>
                  </div>
                </motion.div>
              </AnimatePresence>
            </div>

            <div className="flex items-center gap-2 md:gap-2.5">
              {/* Active doc pill */}
              <AnimatePresence>
                {selectedDocId && (
                  <motion.div
                    initial={{ opacity: 0, scale: 0.9, x: 10 }}
                    animate={{ opacity: 1, scale: 1, x: 0 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-xl text-xs text-purple-300"
                    style={{
                      background: "rgba(124,58,237,0.1)",
                      border: "1px solid rgba(124,58,237,0.22)",
                      backdropFilter: "blur(12px)",
                    }}
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-purple-400 animate-pulse flex-shrink-0" />
                    <span className="truncate max-w-[120px] lg:max-w-[140px]">
                      {documents.find((d) => d.doc_id === selectedDocId)?.name || "Document"}
                    </span>
                  </motion.div>
                )}
              </AnimatePresence>

              {/* AI status */}
              <div className="hidden md:flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs text-emerald-400"
                style={{
                  background: "rgba(16,185,129,0.06)",
                  border: "1px solid rgba(16,185,129,0.15)",
                  backdropFilter: "blur(12px)",
                }}>
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                AI Ready
              </div>

              {/* Feedback — mobile only (desktop uses sidebar button) */}
              <button
                onClick={() => setFeedbackOpen(true)}
                className="md:hidden w-8 h-8 rounded-xl flex items-center justify-center transition-all duration-150"
                style={{ background: "rgba(124,58,237,0.08)", border: "1px solid rgba(124,58,237,0.2)" }}
                title="Feedback & Help"
              >
                <FiMessageCircle size={13} className="text-purple-400" />
              </button>

              {/* Notification bell */}
              <button
                onClick={() => setNotifOpen((o) => !o)}
                className="relative w-8 h-8 rounded-xl flex items-center justify-center transition-all duration-150"
                style={{
                  background: notifOpen ? "rgba(124,58,237,0.18)" : "rgba(255,255,255,0.04)",
                  border: `1px solid ${notifOpen ? "rgba(124,58,237,0.4)" : "rgba(255,255,255,0.06)"}`,
                }}
                onMouseOver={(e) => { e.currentTarget.style.background = "rgba(124,58,237,0.12)"; e.currentTarget.style.borderColor = "rgba(124,58,237,0.3)"; }}
                onMouseOut={(e) => { if (!notifOpen) { e.currentTarget.style.background = "rgba(255,255,255,0.04)"; e.currentTarget.style.borderColor = "rgba(255,255,255,0.06)"; } }}
              >
                <FiBell size={13} className="text-gray-400" />
                {notifications.length > 0 && (
                  <span className="absolute -top-1 -right-1 w-4 h-4 rounded-full text-[9px] font-bold text-white flex items-center justify-center"
                    style={{ background: "linear-gradient(135deg,#7c3aed,#3b82f6)", boxShadow: "0 0 8px rgba(124,58,237,0.6)" }}>
                    {notifications.length > 9 ? "9+" : notifications.length}
                  </span>
                )}
              </button>

              {/* Sign out — mobile only (desktop uses sidebar button) */}
              {user && (
                <button
                  onClick={() => { localStorage.removeItem("studymate_auth"); window.location.href = "/login"; }}
                  className="md:hidden w-8 h-8 rounded-xl flex items-center justify-center transition-all duration-150"
                  style={{ background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)" }}
                  title="Sign Out"
                >
                  <FiLogOut size={13} className="text-gray-400" />
                </button>
              )}

              {/* User avatar (display only — desktop) */}
              {user && (
                <div className="hidden md:flex w-8 h-8 rounded-xl items-center justify-center text-xs font-bold text-white flex-shrink-0"
                  style={{
                    background: "linear-gradient(135deg, #7c3aed, #3b82f6)",
                    boxShadow: "0 0 12px rgba(124,58,237,0.4)",
                  }}
                  title={user.name}
                >
                  {user.name?.[0]?.toUpperCase() || "U"}
                </div>
              )}
            </div>
          </header>

          {/* Content — chat uses flex fill so the input sticks to bottom; others scroll normally */}
          <main
            className={`flex-1 flex flex-col relative ${
              activeSection === "chat" ? "overflow-hidden" : "overflow-y-auto"
            }`}
          >
            <div
              className={`px-3 py-4 md:px-7 md:py-6 ${
                activeSection === "chat" ? "flex-1 flex flex-col overflow-hidden" : ""
              }`}
            >
              <AnimatePresence mode="wait">
                <motion.div
                  key={activeSection}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -8 }}
                  transition={{ duration: 0.28, ease: [0.16, 1, 0.3, 1] }}
                  className={activeSection === "chat" ? "flex-1 flex flex-col overflow-hidden min-h-0" : ""}
                >
                  {activeSection === "upload" && (
                    <FileUpload
                      documents={documents}
                      setDocuments={setDocuments}
                      setSelectedDocId={setSelectedDocId}
                      setActiveSection={setActiveSection}
                      userId={user?.id || 0}
                    />
                  )}
                  {activeSection === "chat" && (
                    <ChatInterface
                      selectedDocId={selectedDocId}
                      documents={documents}
                      userId={user?.id}
                      sessionId={selectedSessionId}
                      onSessionCreated={handleSessionCreated}
                      onNewChat={handleNewChat}
                    />
                  )}
                  {activeSection === "summary" && (
                    <SummaryPanel
                      selectedDocId={selectedDocId}
                      documents={documents}
                      genJob={genJobs[`summary_${selectedDocId}`]}
                      onGenerate={(docId, fn) => startGeneration("summary", docId, fn)}
                    />
                  )}
                  {activeSection === "quiz" && (
                    <QuizPanel
                      selectedDocId={selectedDocId}
                      documents={documents}
                      genJob={genJobs[`quiz_${selectedDocId}`]}
                      onGenerate={(docId, fn) => startGeneration("quiz", docId, fn)}
                    />
                  )}
                  {activeSection === "flashcards" && (
                    <FlashcardPanel
                      selectedDocId={selectedDocId}
                      documents={documents}
                      genJob={genJobs[`flashcards_${selectedDocId}`]}
                      onGenerate={(docId, fn) => startGeneration("flashcards", docId, fn)}
                    />
                  )}
                </motion.div>
              </AnimatePresence>
            </div>
          </main>

        </div>
      </div>
    </>
  );
}
